version: '3.8'

services:
  # Servicio de la API Node.js
  api:
    build:
      context: ./api-nodejs
      dockerfile: Dockerfile
    container_name: concesionario-api
    ports:
      - "3001:3001"
    volumes:
      - ./api-nodejs:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - DB_HOST=mysql
      - DB_USER=concesionario_user
      - DB_PASSWORD=concesionario_pass
      - DB_NAME=concesionario_db
      - DB_PORT=3306
    depends_on:
      - mysql
    restart: unless-stopped
    networks:
      - concesionario-network
      
  # Servicio para el frontend Next.js
  frontend:
    build:
      context: ./frontend-nextjs
      dockerfile: Dockerfile
    container_name: concesionario-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend-nextjs:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - API_URL=http://api:3001
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - concesionario-network

  # Servicio de la base de datos MySQL
  mysql:
    image: mysql:8.0
    container_name: concesionario-mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=concesionario_db
      - MYSQL_USER=concesionario_user
      - MYSQL_PASSWORD=concesionario_pass
    volumes:
      - mysql_data:/var/lib/mysql
      - ./api-nodejs/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    networks:
      - concesionario-network

  # Interfaz de administración para MySQL (opcional)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: concesionario-phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=concesionario_user
      - PMA_PASSWORD=concesionario_pass
      - MYSQL_ROOT_PASSWORD=root_password
      - PMA_ABSOLUTE_URI=http://localhost:8080/
      - PMA_PORT=3306
    depends_on:
      - mysql
    networks:
      - concesionario-network

volumes:
  mysql_data:

networks:
  concesionario-network:
    driver: bridge
