FROM node:18-alpine

# Instalación de netcat para el script de espera
RUN apk add --no-cache netcat-openbsd

WORKDIR /usr/src/app

COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar el código fuente
COPY . .

# Script de espera y ejecución
COPY ./scripts/wait-and-run.sh /usr/src/app/scripts/
RUN chmod +x /usr/src/app/scripts/wait-and-run.sh

CMD ["sh", "/usr/src/app/scripts/wait-and-run.sh"]
